title: POS Kitchen Screen
description: Odoo module to streamline kitchen operations with real-time order updates and progress tracking.
theme: just-the-docs
markdown: kramdown
highlighter: rouge
baseurl: ""
url: ""

search_enabled: true
color_scheme: light

aux_links:
  Odoo Apps:
    - "https://apps.odoo.com/apps/modules/18.0/abichinger_kitchen_screen"
  Demo:
    - "https://odoo-demo.duckdns.org/web#action=point_of_sale.action_pos_config_kanban"

defaults:
  - scope:
      path: ""
    values:
      layout: default


