site_name: POS Kitchen Display (KDS)
# site_url: https://mydomain.org/mysite
theme:
  name: material
nav:
  - Home: index.md
  - Demo: demo.md
  - How-to Guides:
    - Set up a Kitchen Display: guide/displays.md
    - Stages and Alerts: guide/stages.md
    - Item States and Item Routes: guide/item-states-routes.md
    - Preparation Rules: guide/prep-rules.md
    - Dispatchers: guide/dispatchers.md
    - Configure the KDS: guide/configuration.md
    - Printing: guide/printing.md
    - Extensions: guide/extensions.md
  - Troubleshooting: troubleshooting.md
  - Release Notes: release-notes.md